source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '4.1.0'

gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'spring'
  gem 'factory_girl_rails'
end

group :development, :test do
  gem 'pry-rails'
  gem 'rspec-rails'
end

